<a href="https://colab.research.google.com/github/kishore779/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array = np.array([[['A', 'B'],['Z', 'Y']],
                  [['C', 'D'],['I', 'J']],
                  [['E', 'F'],['K', 'J']]])
print(array.shape)
print(array[0,0,0])
word = array[0,0,0]+ array[0,1,1]
print(word)

(3, 2, 2)
A
AY


In [ ]:
## Slicing

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

print(array[1:3])
print(array[::-1])
print("for selecting column")

print(array[:,0])
print("-----------------")
print(array[:,0:3])
print("-----------------")
print(array[:,::-1])

[[ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
for selecting column
[ 1  5  9 13]
-----------------
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
-----------------
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [ ]:
array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
print(array[0:2, 0:2])
print("-----------------")
print(array[0:2,2:])


[[1 2]
 [5 6]]
-----------------
[[3 4]
 [7 8]]


In [ ]:
## Scalar arithmetic

arr = np.array([1,2,3])
print(arr+1)
print(arr-2)
print(arr*3)
print(arr/4)
print(arr**5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [ ]:
## vectorized math func

arr = np.array([1,2,3])
print(np.sqrt(arr))
print(np.round(arr))

[1.         1.41421356 1.73205081]
[1 2 3]


In [ ]:
radii = np.array([1,2,3])
print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [ ]:
## Element wise arithmetic

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
## Comparison Operators

scores = np.array([91,98,78,100,24,64,56])

print(scores >= 70)
print(scores == 100)
print(scores <= 60)

scores[scores < 60] = 0
print(scores)

[ True  True  True  True False False False]
[False False False  True False False False]
[False False False False  True False  True]
[ 91  98  78 100   0  64   0]


In [ ]:
arr1 = np.array([[1,2,3,4]])
arr2 = np.array([[1],[2],[3],[4]])

print(arr1.shape)
print(arr2.shape)
print(arr1 * arr2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(arr1.shape)
print(arr2.shape)
print(arr1 * arr2)

(10,)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
## Aggregate functions

arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.min(arr))
print(np.max(arr))
print(np.var(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print("--------------")

print(np.sum(arr, axis=0)) ## to sum the column
print(np.sum(arr, axis=1)) ## to sum the row wise

55
5.5
2.8722813232690143
1
10
8.25
0
9
--------------
[ 7  9 11 13 15]


In [ ]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22, 15, 99, 18, 19, 21,10]])
teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages <= 65)]
seniors = ages[(ages >= 65)]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]

print(teenagers)
print(adults)
print(seniors)
print(evens)
print(odds)

[17 16 15 10]
[21 19 20 30 18 65 39 22 18 19 21]
[65 99]
[20 16 30 18 22 18 10]
[21 17 19 65 39 15 99 19 21]


In [ ]:
ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22, 15, 99, 18, 19, 21,10]])

adults = np.where(ages >= 18, ages, 0)
print(adults)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 21  0]]


In [ ]:
rng = np.random.default_rng(seed=1)
print(rng.integers(low =1, high=100, size=(3,2)))

[[47 51]
 [75 95]
 [ 4 15]]


In [ ]:
print(np.random.uniform(low=-1, high=1, size=3))

[ 0.17458817 -0.48793237 -0.59402392]


In [ ]:
rng = np.random.default_rng()
array = np.array([1,2,3,4,5])
rng.shuffle(array)
print(array)

[4 2 3 5 1]


In [ ]:
rng = np.random.default_rng()

fruits = np.array(["😤", "❤️", "😘", "💕"])
fruits = rng.choice(fruits, size=(3,3))
print(fruits)

[['❤️' '❤️' '❤️']
 ['💕' '❤️' '😘']
 ['💕' '😤' '❤️']]
